# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/Smart-Dispatch/project>
	:perl_version_from
		_:main;
	:version_from
		_:main;
	:readme_from
		_:main;
	:test_requires
		"Test::Warn",
		"Test::More 0.61";
	:requires
		"Moo",
		"namespace::clean",
		"Sub::Exporter".

_:main
	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>
		"lib/Smart/Dispatch.pm" .

